import {
  GetSession,
  GetUISession,
  SetUISelection,
  ToggleOpenSeries,
  ToggleOpenStory,
  ToggleOpenFolder,
  EnsureOpenSeries,
  EnsureOpenStory,
  EnsureOpenFolder,
  SetRestoreOpen,
  SetLastPen,
  ListWritingTree,
  ListAnalysisCatalog,
  GetAnalysis,
  AnalysisRunQueue,
  RunAnalysis,
  StartAnalysisJob,
  GetAnalysisJobStatus,
  CancelAnalysisJob,
  PersistAnalysisResult,
  SaveAnalysisJobReport,
  ExportMarkdownDocx,
  MatchAnalysisSources,
  ListAnalysisReports,
  GetAnalysisReport,
  GetAnalysisResult,
  ManuscriptChapterStickyContext,
  DeleteAnalysisReport,
  GetCloudAccount,
  ConnectCloudAccount,
  HasCloudAccount,
  OpenBillingCheckout,
  LocalAIStatus,
  GetFolderVisibility,
  ListTemplateFolders,
  SetHiddenFolderNames,
  SetShowHiddenFolders,
  SetFolderOverride,
  GetDraftSection,
  SetDraftSection,
  CreateWritingSeries,
  CreateWritingBook,
  RenameWritingProject,
  DeleteWritingProject,
  ReadDiskFile,
  OpenDiskFile,
  ReadDiskFileRange,
  NeedsChunking,
  ReadDiskFileSections,
  ReadDiskFileSection,
  WriteDiskFileSection,
  WriteDiskFile,
  CreateDiskFile,
  CreateDiskFiles,
  ImportDiskFiles,
  DeleteDiskFile,
  ListPens,
  CreatePen,
  GetSetting,
  PutSetting,
  ReadTextFile,
  ReadImportFiles,
  PickImportFolder,
  AdminListTables,
  AdminTableSchema,
  AdminQueryTable,
  AdminDeleteRow,
  AdminExecSQL,
} from '../../wailsjs/go/main/App'
export const api = {
    getSession: () => GetSession(),
    getUISession: () => GetUISession(),
    setUISelection: (dir, name) => SetUISelection(dir ?? '', name ?? ''),
    toggleOpenSeries: (path) => ToggleOpenSeries(path),
    toggleOpenStory: (path) => ToggleOpenStory(path),
    toggleOpenFolder: (path) => ToggleOpenFolder(path),
    ensureOpenSeries: (path) => EnsureOpenSeries(path),
    ensureOpenStory: (path) => EnsureOpenStory(path),
    ensureOpenFolder: (path) => EnsureOpenFolder(path),
    setRestoreOpen: (on) => SetRestoreOpen(!!on),
    setLastPen: (name) => SetLastPen(name ?? ''),
    listWritingTree: () => ListWritingTree(),
    listAnalysisCatalog: () => ListAnalysisCatalog(),
    getAnalysis: (id) => GetAnalysis(id ?? ''),
    analysisRunQueue: (id) => AnalysisRunQueue(id ?? ''),
    runAnalysis: (id, projectPath) => RunAnalysis(id ?? '', projectPath ?? ''),
    startAnalysisJob: (id, projectPath) => StartAnalysisJob(id ?? '', projectPath ?? ''),
    getAnalysisJobStatus: (jobID) => GetAnalysisJobStatus(jobID ?? ''),
    cancelAnalysisJob: (jobID) => CancelAnalysisJob(jobID ?? ''),
    persistAnalysisResult: (id, projectPath, body, original, proposed, dataJSON) => PersistAnalysisResult(id ?? '', projectPath ?? '', body ?? '', original ?? '', proposed ?? '', dataJSON ?? ''),
    saveAnalysisJobReport: (id, projectPath, body, original, proposed) => SaveAnalysisJobReport(id ?? '', projectPath ?? '', body ?? '', original ?? '', proposed ?? ''),
    exportMarkdownDocx: (markdown, defaultName) => ExportMarkdownDocx(markdown ?? '', defaultName ?? ''),
    matchAnalysisSources: (path) => MatchAnalysisSources(path ?? ''),
    listAnalysisReports: () => ListAnalysisReports(),
    getAnalysisReport: (id) => GetAnalysisReport(id || 0),
    getAnalysisResult: (projectPath, analysisID) => GetAnalysisResult(projectPath ?? '', analysisID ?? ''),
    manuscriptChapterStickyContext: (projectPath, chapterRel) => ManuscriptChapterStickyContext(projectPath ?? '', chapterRel ?? ''),
    deleteAnalysisReport: (id) => DeleteAnalysisReport(id || 0),
    getCloudAccount: () => GetCloudAccount(),
    connectCloudAccount: (email) => ConnectCloudAccount(email ?? ''),
    hasCloudAccount: () => HasCloudAccount(),
    openBillingCheckout: () => OpenBillingCheckout(),
    localAIStatus: () => LocalAIStatus(),
    getFolderVisibility: () => GetFolderVisibility(),
    listTemplateFolders: () => ListTemplateFolders(),
    setHiddenFolderNames: (names) => SetHiddenFolderNames({ names: names || [] }),
    setShowHiddenFolders: (on) => SetShowHiddenFolders(!!on),
    setFolderOverride: (projectPath, key, mode) => SetFolderOverride({
        project_path: projectPath,
        key,
        mode: mode ?? '',
    }),
    getDraftSection: () => GetDraftSection(),
    setDraftSection: (value, rename) => SetDraftSection(value, !!rename),
    createWritingSeries: (data) => CreateWritingSeries({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: '',
    }),
    createWritingBook: (data) => CreateWritingBook({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: data.series_path ?? '',
    }),
    renameWritingProject: (path, name) => RenameWritingProject(path, name),
    deleteWritingProject: (path) => DeleteWritingProject(path),
    readDiskFile: (dir, name) => ReadDiskFile(dir, name),
    openDiskFile: (dir, name) => OpenDiskFile(dir, name),
    readDiskFileRange: (dir, name, offset, limit) => ReadDiskFileRange(dir, name, offset, limit),
    needsChunking: (dir, name) => NeedsChunking(dir, name),
    readDiskFileSections: (dir, name) => ReadDiskFileSections(dir, name),
    readDiskFileSection: (dir, name, index) => ReadDiskFileSection(dir, name, index),
    writeDiskFileSection: (dir, name, index, text) => WriteDiskFileSection(dir, name, index, text),
    writeDiskFile: (data) => WriteDiskFile(data),
    createDiskFile: (dir, name, text) => CreateDiskFile(dir, name, text ?? ''),
    createDiskFiles: (dir, files) => CreateDiskFiles(dir, files || []),
    importDiskFiles: (dir, paths) => ImportDiskFiles(dir, paths || []),
    deleteDiskFile: (dir, name) => DeleteDiskFile(dir, name),
    listPens: () => ListPens(),
    createPen: (name) => CreatePen(name),
    getSetting: (key) => GetSetting(key),
    putSetting: (key, value) => PutSetting(key, value),
    readTextFile: (path) => ReadTextFile(path),
    readImportFiles: (paths) => ReadImportFiles(paths),
    pickImportFolder: () => PickImportFolder(),
    adminListTables: () => AdminListTables(),
    adminTableSchema: (table) => AdminTableSchema(table),
    adminQueryTable: (table, limit, offset) => AdminQueryTable(table, limit, offset),
    adminDeleteRow: (table, id) => AdminDeleteRow(table, id),
    adminExecSQL: (sql) => AdminExecSQL(sql),
};
