import {
  GetSession,
  ListWritingTree,
  CreateWritingSeries,
  CreateWritingBook,
  RenameWritingProject,
  DeleteWritingProject,
  ListHeaderFiles,
  ReadHeaderFile,
  WriteHeaderFile,
  CreateHeaderFile,
  DeleteHeaderFile,
  PlaceHeaderFiles,
  ListHeaderOverrides,
  SetHeaderOverride,
  ClearHeaderOverride,
  ListDocumentTypes,
  ListPens,
  CreatePen,
  GetSetting,
  PutSetting,
  ReadTextFile,
  ReadImportFiles,
  PickImportFolder,
  AdminListTables,
  AdminTableSchema,
  AdminQueryTable,
  AdminDeleteRow,
  AdminExecSQL,
} from '../../wailsjs/go/main/App'
export const api = {
    getSession: () => GetSession(),
    listWritingTree: () => ListWritingTree(),
    createWritingSeries: (data) => CreateWritingSeries({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: '',
    }),
    createWritingBook: (data) => CreateWritingBook({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: data.series_path ?? '',
    }),
    renameWritingProject: (path, name) => RenameWritingProject(path, name),
    deleteWritingProject: (path) => DeleteWritingProject(path),
    listHeaderFiles: (projectPath, projectKind, kind) => ListHeaderFiles(projectPath, projectKind, kind),
    readHeaderFile: (ref) => ReadHeaderFile(ref),
    writeHeaderFile: (data) => WriteHeaderFile(data),
    createHeaderFile: (data) => CreateHeaderFile(data),
    deleteHeaderFile: (ref) => DeleteHeaderFile(ref),
    placeHeaderFiles: (data) => PlaceHeaderFiles(data),
    listHeaderOverrides: (projectPath) => ListHeaderOverrides(projectPath),
    setHeaderOverride: (projectPath, kind, path) => SetHeaderOverride(projectPath, kind, path),
    clearHeaderOverride: (projectPath, kind) => ClearHeaderOverride(projectPath, kind),
    listDocumentTypes: () => ListDocumentTypes(),
    listPens: () => ListPens(),
    createPen: (name) => CreatePen(name),
    getSetting: (key) => GetSetting(key),
    putSetting: (key, value) => PutSetting(key, value),
    readTextFile: (path) => ReadTextFile(path),
    readImportFiles: (paths) => ReadImportFiles(paths),
    pickImportFolder: () => PickImportFolder(),
    adminListTables: () => AdminListTables(),
    adminTableSchema: (table) => AdminTableSchema(table),
    adminQueryTable: (table, limit, offset) => AdminQueryTable(table, limit, offset),
    adminDeleteRow: (table, id) => AdminDeleteRow(table, id),
    adminExecSQL: (sql) => AdminExecSQL(sql),
};
