import {
  GetSession,
  GetUISession,
  SetUISelection,
  ToggleOpenSeries,
  ToggleOpenStory,
  ToggleOpenFolder,
  EnsureOpenSeries,
  EnsureOpenStory,
  EnsureOpenFolder,
  SetRestoreOpen,
  SetLastPen,
  ListWritingTree,
  ListAnalysisCatalog,
  GetAnalysis,
  MatchAnalysisSources,
  GetFolderVisibility,
  ListTemplateFolders,
  SetHiddenFolderNames,
  SetShowHiddenFolders,
  SetFolderOverride,
  GetDraftSection,
  SetDraftSection,
  CreateWritingSeries,
  CreateWritingBook,
  RenameWritingProject,
  DeleteWritingProject,
  ReadDiskFile,
  WriteDiskFile,
  CreateDiskFile,
  CreateDiskFiles,
  ImportDiskFiles,
  DeleteDiskFile,
  ListPens,
  CreatePen,
  GetSetting,
  PutSetting,
  ReadTextFile,
  ReadImportFiles,
  PickImportFolder,
  AdminListTables,
  AdminTableSchema,
  AdminQueryTable,
  AdminDeleteRow,
  AdminExecSQL,
} from '../../wailsjs/go/main/App'
export const api = {
    getSession: () => GetSession(),
    getUISession: () => GetUISession(),
    setUISelection: (dir, name) => SetUISelection(dir ?? '', name ?? ''),
    toggleOpenSeries: (path) => ToggleOpenSeries(path),
    toggleOpenStory: (path) => ToggleOpenStory(path),
    toggleOpenFolder: (path) => ToggleOpenFolder(path),
    ensureOpenSeries: (path) => EnsureOpenSeries(path),
    ensureOpenStory: (path) => EnsureOpenStory(path),
    ensureOpenFolder: (path) => EnsureOpenFolder(path),
    setRestoreOpen: (on) => SetRestoreOpen(!!on),
    setLastPen: (name) => SetLastPen(name ?? ''),
    listWritingTree: () => ListWritingTree(),
    listAnalysisCatalog: () => ListAnalysisCatalog(),
    getAnalysis: (id) => GetAnalysis(id ?? ''),
    matchAnalysisSources: (path) => MatchAnalysisSources(path ?? ''),
    getFolderVisibility: () => GetFolderVisibility(),
    listTemplateFolders: () => ListTemplateFolders(),
    setHiddenFolderNames: (names) => SetHiddenFolderNames({ names: names || [] }),
    setShowHiddenFolders: (on) => SetShowHiddenFolders(!!on),
    setFolderOverride: (projectPath, key, mode) => SetFolderOverride({
        project_path: projectPath,
        key,
        mode: mode ?? '',
    }),
    getDraftSection: () => GetDraftSection(),
    setDraftSection: (value, rename) => SetDraftSection(value, !!rename),
    createWritingSeries: (data) => CreateWritingSeries({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: '',
    }),
    createWritingBook: (data) => CreateWritingBook({
        pen_name: data.pen_name ?? '',
        pen_path: data.pen_path ?? '',
        name: data.name,
        series_path: data.series_path ?? '',
    }),
    renameWritingProject: (path, name) => RenameWritingProject(path, name),
    deleteWritingProject: (path) => DeleteWritingProject(path),
    readDiskFile: (dir, name) => ReadDiskFile(dir, name),
    writeDiskFile: (data) => WriteDiskFile(data),
    createDiskFile: (dir, name, text) => CreateDiskFile(dir, name, text ?? ''),
    createDiskFiles: (dir, files) => CreateDiskFiles(dir, files || []),
    importDiskFiles: (dir, paths) => ImportDiskFiles(dir, paths || []),
    deleteDiskFile: (dir, name) => DeleteDiskFile(dir, name),
    listPens: () => ListPens(),
    createPen: (name) => CreatePen(name),
    getSetting: (key) => GetSetting(key),
    putSetting: (key, value) => PutSetting(key, value),
    readTextFile: (path) => ReadTextFile(path),
    readImportFiles: (paths) => ReadImportFiles(paths),
    pickImportFolder: () => PickImportFolder(),
    adminListTables: () => AdminListTables(),
    adminTableSchema: (table) => AdminTableSchema(table),
    adminQueryTable: (table, limit, offset) => AdminQueryTable(table, limit, offset),
    adminDeleteRow: (table, id) => AdminDeleteRow(table, id),
    adminExecSQL: (sql) => AdminExecSQL(sql),
};
