const features = [
  {
    title: "Local-First Privacy",
    description:
      "Your manuscripts never leave your machine. Loremetry stores everything in a local database — no cloud uploads required.",
    icon: "🔒",
  },
  {
    title: "AI-Powered Analysis",
    description:
      "Get detailed craft reports on show-don't-tell, pacing, tension, dialogue, and more — all generated by advanced language models.",
    icon: "🧠",
  },
  {
    title: "Multiple Report Types",
    description:
      "From Zeigarnik tension maps to print-production checklists, choose the analysis that fits your stage of writing.",
    icon: "📊",
  },
  {
    title: "Works Offline",
    description:
      "Local analyses like line polish, vellum prep, and print production run entirely on your machine — no internet needed.",
    icon: "⚡",
  },
  {
    title: "Project Organization",
    description:
      "Import manuscript folders, track chapters and scenes, and keep all your analysis reports in one place.",
    icon: "📁",
  },
  {
    title: "Built for Writers",
    description:
      "Designed specifically for fiction and non-fiction authors. Not a generic grammar tool — a craft companion.",
    icon: "✍️",
  },
];

export default function Features() {
  return (
    <section id="features" className="bg-slate-50 py-24">
      <div className="mx-auto max-w-6xl px-6">
        <h2 className="text-center text-3xl font-bold tracking-tight sm:text-4xl">
          Everything you need to refine your manuscript
        </h2>
        <p className="mx-auto mt-4 max-w-2xl text-center text-lg text-slate-600">
          Loremetry combines local-first privacy with the power of AI to give
          you actionable feedback on your writing craft.
        </p>

        <div className="mt-16 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f) => (
            <div
              key={f.title}
              className="rounded-xl border border-slate-200 bg-white p-8 shadow-sm transition hover:shadow-md"
            >
              <div className="text-3xl">{f.icon}</div>
              <h3 className="mt-4 text-lg font-semibold">{f.title}</h3>
              <p className="mt-2 text-slate-600 leading-relaxed">
                {f.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
