// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdminDeleteRow(arg1, arg2) {
  return window['go']['main']['App']['AdminDeleteRow'](arg1, arg2);
}

export function AdminExecSQL(arg1) {
  return window['go']['main']['App']['AdminExecSQL'](arg1);
}

export function AdminListTables() {
  return window['go']['main']['App']['AdminListTables']();
}

export function AdminQueryTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdminQueryTable'](arg1, arg2, arg3);
}

export function AdminTableSchema(arg1) {
  return window['go']['main']['App']['AdminTableSchema'](arg1);
}

export function ClearFolderLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClearFolderLink'](arg1, arg2, arg3);
}

export function ClearHeaderOverride(arg1, arg2) {
  return window['go']['main']['App']['ClearHeaderOverride'](arg1, arg2);
}

export function CreateAct(arg1, arg2) {
  return window['go']['main']['App']['CreateAct'](arg1, arg2);
}

export function CreateChapter(arg1, arg2) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2);
}

export function CreateCharacter(arg1) {
  return window['go']['main']['App']['CreateCharacter'](arg1);
}

export function CreateDiskFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateDiskFile'](arg1, arg2, arg3);
}

export function CreateDiskFiles(arg1, arg2) {
  return window['go']['main']['App']['CreateDiskFiles'](arg1, arg2);
}

export function CreateHeaderFile(arg1) {
  return window['go']['main']['App']['CreateHeaderFile'](arg1);
}

export function CreatePen(arg1) {
  return window['go']['main']['App']['CreatePen'](arg1);
}

export function CreateSeries(arg1) {
  return window['go']['main']['App']['CreateSeries'](arg1);
}

export function CreateSeriesDoc(arg1, arg2) {
  return window['go']['main']['App']['CreateSeriesDoc'](arg1, arg2);
}

export function CreateStory(arg1) {
  return window['go']['main']['App']['CreateStory'](arg1);
}

export function CreateStoryDoc(arg1, arg2) {
  return window['go']['main']['App']['CreateStoryDoc'](arg1, arg2);
}

export function CreateWritingBook(arg1) {
  return window['go']['main']['App']['CreateWritingBook'](arg1);
}

export function CreateWritingSeries(arg1) {
  return window['go']['main']['App']['CreateWritingSeries'](arg1);
}

export function DeleteAct(arg1) {
  return window['go']['main']['App']['DeleteAct'](arg1);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteCharacter(arg1) {
  return window['go']['main']['App']['DeleteCharacter'](arg1);
}

export function DeleteDiskFile(arg1, arg2) {
  return window['go']['main']['App']['DeleteDiskFile'](arg1, arg2);
}

export function DeleteHeaderFile(arg1) {
  return window['go']['main']['App']['DeleteHeaderFile'](arg1);
}

export function DeleteSeries(arg1) {
  return window['go']['main']['App']['DeleteSeries'](arg1);
}

export function DeleteSeriesDoc(arg1) {
  return window['go']['main']['App']['DeleteSeriesDoc'](arg1);
}

export function DeleteStory(arg1) {
  return window['go']['main']['App']['DeleteStory'](arg1);
}

export function DeleteWritingProject(arg1) {
  return window['go']['main']['App']['DeleteWritingProject'](arg1);
}

export function EnsureOpenFolder(arg1) {
  return window['go']['main']['App']['EnsureOpenFolder'](arg1);
}

export function EnsureOpenSeries(arg1) {
  return window['go']['main']['App']['EnsureOpenSeries'](arg1);
}

export function EnsureOpenStory(arg1) {
  return window['go']['main']['App']['EnsureOpenStory'](arg1);
}

export function GetAct(arg1) {
  return window['go']['main']['App']['GetAct'](arg1);
}

export function GetAnalysis(arg1) {
  return window['go']['main']['App']['GetAnalysis'](arg1);
}

export function GetAnalysisReport(arg1) {
  return window['go']['main']['App']['GetAnalysisReport'](arg1);
}

export function GetCloudAccount() {
  return window['go']['main']['App']['GetCloudAccount']();
}

export function GetChapter(arg1) {
  return window['go']['main']['App']['GetChapter'](arg1);
}

export function GetCharacter(arg1) {
  return window['go']['main']['App']['GetCharacter'](arg1);
}

export function GetDraftSection() {
  return window['go']['main']['App']['GetDraftSection']();
}

export function GetFolderVisibility() {
  return window['go']['main']['App']['GetFolderVisibility']();
}

export function GetSeriesBible(arg1) {
  return window['go']['main']['App']['GetSeriesBible'](arg1);
}

export function GetSeriesDoc(arg1) {
  return window['go']['main']['App']['GetSeriesDoc'](arg1);
}

export function GetSession() {
  return window['go']['main']['App']['GetSession']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetUISession() {
  return window['go']['main']['App']['GetUISession']();
}

export function ImportDiskFiles(arg1, arg2) {
  return window['go']['main']['App']['ImportDiskFiles'](arg1, arg2);
}

export function ListActs(arg1) {
  return window['go']['main']['App']['ListActs'](arg1);
}

export function ListAnalysisReports() {
  return window['go']['main']['App']['ListAnalysisReports']();
}

export function ListAnalysisCatalog() {
  return window['go']['main']['App']['ListAnalysisCatalog']();
}

export function ListChapters(arg1) {
  return window['go']['main']['App']['ListChapters'](arg1);
}

export function ListCharacters(arg1) {
  return window['go']['main']['App']['ListCharacters'](arg1);
}

export function ListDocumentTypes() {
  return window['go']['main']['App']['ListDocumentTypes']();
}

export function ListFolderLinks(arg1, arg2) {
  return window['go']['main']['App']['ListFolderLinks'](arg1, arg2);
}

export function ListHeaderFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListHeaderFiles'](arg1, arg2, arg3);
}

export function ListHeaderOverrides(arg1) {
  return window['go']['main']['App']['ListHeaderOverrides'](arg1);
}

export function ListPens() {
  return window['go']['main']['App']['ListPens']();
}

export function ListSeries() {
  return window['go']['main']['App']['ListSeries']();
}

export function ListSeriesCharacters(arg1) {
  return window['go']['main']['App']['ListSeriesCharacters'](arg1);
}

export function ListSeriesDocs(arg1) {
  return window['go']['main']['App']['ListSeriesDocs'](arg1);
}

export function ListStories(arg1) {
  return window['go']['main']['App']['ListStories'](arg1);
}

export function ListStoryDocs(arg1) {
  return window['go']['main']['App']['ListStoryDocs'](arg1);
}

export function ListTemplateFolders() {
  return window['go']['main']['App']['ListTemplateFolders']();
}

export function ListWritingTree() {
  return window['go']['main']['App']['ListWritingTree']();
}

export function MatchAnalysisSources(arg1) {
  return window['go']['main']['App']['MatchAnalysisSources'](arg1);
}

export function PickImportFolder() {
  return window['go']['main']['App']['PickImportFolder']();
}

export function PlaceHeaderFiles(arg1) {
  return window['go']['main']['App']['PlaceHeaderFiles'](arg1);
}

export function PlaceSeriesDoc(arg1, arg2) {
  return window['go']['main']['App']['PlaceSeriesDoc'](arg1, arg2);
}

export function PlaceStoryDoc(arg1, arg2) {
  return window['go']['main']['App']['PlaceStoryDoc'](arg1, arg2);
}

export function PutSetting(arg1, arg2) {
  return window['go']['main']['App']['PutSetting'](arg1, arg2);
}

export function ReadDiskFile(arg1, arg2) {
  return window['go']['main']['App']['ReadDiskFile'](arg1, arg2);
}

export function ReadHeaderFile(arg1) {
  return window['go']['main']['App']['ReadHeaderFile'](arg1);
}

export function ReadImportFiles(arg1) {
  return window['go']['main']['App']['ReadImportFiles'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['main']['App']['ReadTextFile'](arg1);
}

export function RenameWritingProject(arg1, arg2) {
  return window['go']['main']['App']['RenameWritingProject'](arg1, arg2);
}

export function ReorderActs(arg1, arg2) {
  return window['go']['main']['App']['ReorderActs'](arg1, arg2);
}

export function ReorderStories(arg1, arg2) {
  return window['go']['main']['App']['ReorderStories'](arg1, arg2);
}

export function OpenBillingCheckout() {
  return window['go']['main']['App']['OpenBillingCheckout']();
}

export function ConnectCloudAccount(arg1) {
  return window['go']['main']['App']['ConnectCloudAccount'](arg1);
}

export function HasCloudAccount() {
  return window['go']['main']['App']['HasCloudAccount']();
}

export function RunAnalysis(arg1, arg2) {
  return window['go']['main']['App']['RunAnalysis'](arg1, arg2);
}

export function SetDraftSection(arg1, arg2) {
  return window['go']['main']['App']['SetDraftSection'](arg1, arg2);
}

export function SetFolderLink(arg1) {
  return window['go']['main']['App']['SetFolderLink'](arg1);
}

export function SetFolderOverride(arg1) {
  return window['go']['main']['App']['SetFolderOverride'](arg1);
}

export function SetHeaderOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetHeaderOverride'](arg1, arg2, arg3);
}

export function SetHiddenFolderNames(arg1) {
  return window['go']['main']['App']['SetHiddenFolderNames'](arg1);
}

export function SetLastPen(arg1) {
  return window['go']['main']['App']['SetLastPen'](arg1);
}

export function SetRestoreOpen(arg1) {
  return window['go']['main']['App']['SetRestoreOpen'](arg1);
}

export function SetShowHiddenFolders(arg1) {
  return window['go']['main']['App']['SetShowHiddenFolders'](arg1);
}

export function SetUISelection(arg1, arg2) {
  return window['go']['main']['App']['SetUISelection'](arg1, arg2);
}

export function SyncAllFolders() {
  return window['go']['main']['App']['SyncAllFolders']();
}

export function ToggleOpenFolder(arg1) {
  return window['go']['main']['App']['ToggleOpenFolder'](arg1);
}

export function ToggleOpenSeries(arg1) {
  return window['go']['main']['App']['ToggleOpenSeries'](arg1);
}

export function ToggleOpenStory(arg1) {
  return window['go']['main']['App']['ToggleOpenStory'](arg1);
}

export function UpdateAct(arg1, arg2) {
  return window['go']['main']['App']['UpdateAct'](arg1, arg2);
}

export function UpdateChapter(arg1, arg2) {
  return window['go']['main']['App']['UpdateChapter'](arg1, arg2);
}

export function UpdateCharacter(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharacter'](arg1, arg2);
}

export function UpdateSeries(arg1, arg2) {
  return window['go']['main']['App']['UpdateSeries'](arg1, arg2);
}

export function UpdateSeriesBible(arg1, arg2) {
  return window['go']['main']['App']['UpdateSeriesBible'](arg1, arg2);
}

export function UpdateSeriesDoc(arg1, arg2) {
  return window['go']['main']['App']['UpdateSeriesDoc'](arg1, arg2);
}

export function UpdateStory(arg1, arg2) {
  return window['go']['main']['App']['UpdateStory'](arg1, arg2);
}

export function WriteDiskFile(arg1) {
  return window['go']['main']['App']['WriteDiskFile'](arg1);
}

export function WriteHeaderFile(arg1) {
  return window['go']['main']['App']['WriteHeaderFile'](arg1);
}
