// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {main} from '../models';

export function AdminDeleteRow(arg1:string,arg2:number):Promise<store.DeletedResult>;

export function AdminExecSQL(arg1:string):Promise<store.AdminSQLResult>;

export function AdminListTables():Promise<store.AdminTables>;

export function AdminQueryTable(arg1:string,arg2:number,arg3:number):Promise<store.AdminTableRows>;

export function AdminTableSchema(arg1:string):Promise<store.AdminSchema>;

export function ClearFolderLink(arg1:string,arg2:number,arg3:string):Promise<store.DeletedResult>;

export function ClearHeaderOverride(arg1:string,arg2:string):Promise<store.DeletedResult>;

export function CreateAct(arg1:number,arg2:store.ActInput):Promise<store.IDResult>;

export function CreateChapter(arg1:number,arg2:store.ChapterInput):Promise<store.IDResult>;

export function CreateCharacter(arg1:store.CharacterInput):Promise<store.IDResult>;

export function CreateHeaderFile(arg1:store.HeaderFileWrite):Promise<store.HeaderFile>;

export function CreatePen(arg1:string):Promise<store.Pen>;

export function CreateSeries(arg1:store.SeriesInput):Promise<store.IDResult>;

export function CreateSeriesDoc(arg1:number,arg2:store.SeriesDocInput):Promise<store.IDResult>;

export function CreateStory(arg1:store.StoryInput):Promise<store.IDResult>;

export function CreateStoryDoc(arg1:number,arg2:store.DocInput):Promise<store.IDResult>;

export function CreateWritingBook(arg1:store.WritingProjectInput):Promise<store.PathResult>;

export function CreateWritingSeries(arg1:store.WritingProjectInput):Promise<store.PathResult>;

export function DeleteAct(arg1:number):Promise<store.DeletedResult>;

export function DeleteChapter(arg1:number):Promise<store.DeletedResult>;

export function DeleteCharacter(arg1:number):Promise<store.DeletedResult>;

export function DeleteHeaderFile(arg1:store.HeaderFileRef):Promise<store.DeletedResult>;

export function DeleteSeries(arg1:number):Promise<store.DeletedResult>;

export function DeleteSeriesDoc(arg1:number):Promise<store.DeletedResult>;

export function DeleteStory(arg1:number):Promise<store.DeletedResult>;

export function DeleteWritingProject(arg1:string):Promise<store.DeletedResult>;

export function GetAct(arg1:number):Promise<store.StoryAct>;

export function GetChapter(arg1:number):Promise<store.Chapter>;

export function GetCharacter(arg1:number):Promise<store.CharacterProfile>;

export function GetSeriesBible(arg1:number):Promise<store.BibleDoc>;

export function GetSeriesDoc(arg1:number):Promise<store.BibleDoc>;

export function GetSession():Promise<store.AuthSession>;

export function GetSetting(arg1:string):Promise<store.SettingValue>;

export function ListActs(arg1:number):Promise<Array<store.StoryAct>>;

export function ListChapters(arg1:number):Promise<Array<store.Chapter>>;

export function ListCharacters(arg1:number):Promise<Array<store.CharacterProfile>>;

export function ListDocumentTypes():Promise<Array<store.DocumentType>>;

export function ListFolderLinks(arg1:string,arg2:number):Promise<Array<store.FolderLink>>;

export function ListHeaderFiles(arg1:string,arg2:string,arg3:string):Promise<store.HeaderList>;

export function ListHeaderOverrides(arg1:string):Promise<Array<store.FolderLink>>;

export function ListPens():Promise<Array<store.Pen>>;

export function ListSeries():Promise<Array<store.Series>>;

export function ListSeriesCharacters(arg1:number):Promise<Array<store.CharacterProfile>>;

export function ListSeriesDocs(arg1:number):Promise<Array<store.SeriesDoc>>;

export function ListStories(arg1:number):Promise<Array<store.Story>>;

export function ListStoryDocs(arg1:number):Promise<Array<store.StoryDoc>>;

export function ListWritingTree():Promise<store.WritingTree>;

export function PickImportFolder():Promise<string>;

export function PlaceHeaderFiles(arg1:store.HeaderPlaceInput):Promise<store.UpdatedResult>;

export function PlaceSeriesDoc(arg1:number,arg2:store.PlaceInput):Promise<store.UpdatedResult>;

export function PlaceStoryDoc(arg1:number,arg2:store.PlaceInput):Promise<store.UpdatedResult>;

export function PutSetting(arg1:string,arg2:string):Promise<store.SettingValue>;

export function ReadHeaderFile(arg1:store.HeaderFileRef):Promise<store.HeaderFileContent>;

export function ReadImportFiles(arg1:Array<string>):Promise<Array<main.ImportedFile>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RenameWritingProject(arg1:string,arg2:string):Promise<store.PathResult>;

export function ReorderActs(arg1:number,arg2:store.IDList):Promise<store.UpdatedResult>;

export function ReorderStories(arg1:number,arg2:store.IDList):Promise<store.UpdatedResult>;

export function SetFolderLink(arg1:store.FolderLinkInput):Promise<store.FolderLink>;

export function SetHeaderOverride(arg1:string,arg2:string,arg3:string):Promise<store.FolderLink>;

export function SyncAllFolders():Promise<Array<store.FolderChange>>;

export function UpdateAct(arg1:number,arg2:store.ActInput):Promise<store.UpdatedResult>;

export function UpdateChapter(arg1:number,arg2:store.ChapterInput):Promise<store.UpdatedResult>;

export function UpdateCharacter(arg1:number,arg2:store.CharacterInput):Promise<store.UpdatedResult>;

export function UpdateSeries(arg1:number,arg2:store.SeriesInput):Promise<store.UpdatedResult>;

export function UpdateSeriesBible(arg1:number,arg2:string):Promise<store.UpdatedResult>;

export function UpdateSeriesDoc(arg1:number,arg2:store.SeriesDocInput):Promise<store.UpdatedResult>;

export function UpdateStory(arg1:number,arg2:store.StoryInput):Promise<store.UpdatedResult>;

export function WriteHeaderFile(arg1:store.HeaderFileWrite):Promise<store.HeaderFile>;
