// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {cloud} from '../models';
import {main} from '../models';

export function AdminDeleteRow(arg1:string,arg2:number):Promise<store.DeletedResult>;

export function AdminExecSQL(arg1:string):Promise<store.AdminSQLResult>;

export function AdminListTables():Promise<store.AdminTables>;

export function AdminQueryTable(arg1:string,arg2:number,arg3:number):Promise<store.AdminTableRows>;

export function AdminTableSchema(arg1:string):Promise<store.AdminSchema>;

export function ClearFolderLink(arg1:string,arg2:number,arg3:string):Promise<store.DeletedResult>;

export function ClearHeaderOverride(arg1:string,arg2:string):Promise<store.DeletedResult>;

export function ConnectCloudAccount(arg1:string):Promise<cloud.Account>;

export function CreateAct(arg1:number,arg2:store.ActInput):Promise<store.IDResult>;

export function CreateChapter(arg1:number,arg2:store.ChapterInput):Promise<store.IDResult>;

export function CreateCharacter(arg1:store.CharacterInput):Promise<store.IDResult>;

export function CreateDiskFile(arg1:string,arg2:string,arg3:string):Promise<store.DiskFile>;

export function CreateDiskFiles(arg1:string,arg2:Array<store.IncomingFile>):Promise<store.DiskFile>;

export function CreateHeaderFile(arg1:store.HeaderFileWrite):Promise<store.HeaderFile>;

export function CreatePen(arg1:string):Promise<store.Pen>;

export function CreateSeries(arg1:store.SeriesInput):Promise<store.IDResult>;

export function CreateSeriesDoc(arg1:number,arg2:store.SeriesDocInput):Promise<store.IDResult>;

export function CreateStory(arg1:store.StoryInput):Promise<store.IDResult>;

export function CreateStoryDoc(arg1:number,arg2:store.DocInput):Promise<store.IDResult>;

export function CreateWritingBook(arg1:store.WritingProjectInput):Promise<store.PathResult>;

export function CreateWritingSeries(arg1:store.WritingProjectInput):Promise<store.PathResult>;

export function DeleteAct(arg1:number):Promise<store.DeletedResult>;

export function DeleteAnalysisReport(arg1:number):Promise<void>;

export function DeleteChapter(arg1:number):Promise<store.DeletedResult>;

export function DeleteCharacter(arg1:number):Promise<store.DeletedResult>;

export function DeleteDiskFile(arg1:string,arg2:string):Promise<store.DeletedResult>;

export function DeleteHeaderFile(arg1:store.HeaderFileRef):Promise<store.DeletedResult>;

export function DeleteSeries(arg1:number):Promise<store.DeletedResult>;

export function DeleteSeriesDoc(arg1:number):Promise<store.DeletedResult>;

export function DeleteStory(arg1:number):Promise<store.DeletedResult>;

export function DeleteWritingProject(arg1:string):Promise<store.DeletedResult>;

export function EnsureOpenFolder(arg1:string):Promise<store.UISession>;

export function EnsureOpenSeries(arg1:string):Promise<store.UISession>;

export function EnsureOpenStory(arg1:string):Promise<store.UISession>;

export function GetAct(arg1:number):Promise<store.StoryAct>;

export function GetAnalysis(arg1:string):Promise<store.AnalysisDetail>;

export function GetAnalysisJobStatus(arg1:string):Promise<cloud.JobStatus>;

export function GetAnalysisReport(arg1:number):Promise<store.AnalysisReport>;

export function GetChapter(arg1:number):Promise<store.Chapter>;

export function GetCharacter(arg1:number):Promise<store.CharacterProfile>;

export function GetCloudAccount():Promise<cloud.Account>;

export function GetDraftSection():Promise<string>;

export function GetFolderVisibility():Promise<store.FolderVisibility>;

export function GetSeriesBible(arg1:number):Promise<store.BibleDoc>;

export function GetSeriesDoc(arg1:number):Promise<store.BibleDoc>;

export function GetSession():Promise<store.AuthSession>;

export function GetSetting(arg1:string):Promise<store.SettingValue>;

export function GetUISession():Promise<store.UISession>;

export function HasCloudAccount():Promise<boolean>;

export function ImportDiskFiles(arg1:string,arg2:Array<string>):Promise<store.DiskFile>;

export function ListActs(arg1:number):Promise<Array<store.StoryAct>>;

export function ListAnalysisCatalog():Promise<Array<store.AnalysisGroup>>;

export function ListAnalysisReports():Promise<Array<store.AnalysisReport>>;

export function ListChapters(arg1:number):Promise<Array<store.Chapter>>;

export function ListCharacters(arg1:number):Promise<Array<store.CharacterProfile>>;

export function ListDocumentTypes():Promise<Array<store.DocumentType>>;

export function ListFolderLinks(arg1:string,arg2:number):Promise<Array<store.FolderLink>>;

export function ListHeaderFiles(arg1:string,arg2:string,arg3:string):Promise<store.HeaderList>;

export function ListHeaderOverrides(arg1:string):Promise<Array<store.FolderLink>>;

export function ListPens():Promise<Array<store.Pen>>;

export function ListSeries():Promise<Array<store.Series>>;

export function ListSeriesCharacters(arg1:number):Promise<Array<store.CharacterProfile>>;

export function ListSeriesDocs(arg1:number):Promise<Array<store.SeriesDoc>>;

export function ListStories(arg1:number):Promise<Array<store.Story>>;

export function ListStoryDocs(arg1:number):Promise<Array<store.StoryDoc>>;

export function ListTemplateFolders():Promise<store.TemplateFolderLists>;

export function ListWritingTree():Promise<store.WritingTree>;

export function MatchAnalysisSources(arg1:string):Promise<store.AnalysisSources>;

export function NeedsChunking(arg1:string,arg2:string):Promise<boolean>;

export function OpenBillingCheckout():Promise<void>;

export function OpenDiskFile(arg1:string,arg2:string):Promise<store.OpenedFile>;

export function PickImportFolder():Promise<string>;

export function PlaceHeaderFiles(arg1:store.HeaderPlaceInput):Promise<store.UpdatedResult>;

export function PlaceSeriesDoc(arg1:number,arg2:store.PlaceInput):Promise<store.UpdatedResult>;

export function PlaceStoryDoc(arg1:number,arg2:store.PlaceInput):Promise<store.UpdatedResult>;

export function PutSetting(arg1:string,arg2:string):Promise<store.SettingValue>;

export function ReadDiskFile(arg1:string,arg2:string):Promise<store.DiskFile>;

export function ReadDiskFileRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<store.FileRange>;

export function ReadDiskFileSection(arg1:string,arg2:string,arg3:number):Promise<store.FileSectionContent>;

export function ReadDiskFileSections(arg1:string,arg2:string):Promise<store.FileSections>;

export function ReadHeaderFile(arg1:store.HeaderFileRef):Promise<store.HeaderFileContent>;

export function ReadImportFiles(arg1:Array<string>):Promise<Array<main.ImportedFile>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RenameWritingProject(arg1:string,arg2:string):Promise<store.PathResult>;

export function ReorderActs(arg1:number,arg2:store.IDList):Promise<store.UpdatedResult>;

export function ReorderStories(arg1:number,arg2:store.IDList):Promise<store.UpdatedResult>;

export function RunAnalysis(arg1:string,arg2:string):Promise<store.AnalysisReport>;

export function SaveAnalysisJobReport(arg1:string,arg2:string,arg3:string):Promise<store.AnalysisReport>;

export function SetDraftSection(arg1:string,arg2:boolean):Promise<store.RenameCount>;

export function SetFolderLink(arg1:store.FolderLinkInput):Promise<store.FolderLink>;

export function SetFolderOverride(arg1:store.FolderOverrideInput):Promise<store.FolderVisibility>;

export function SetHeaderOverride(arg1:string,arg2:string,arg3:string):Promise<store.FolderLink>;

export function SetHiddenFolderNames(arg1:store.NameList):Promise<store.FolderVisibility>;

export function SetLastPen(arg1:string):Promise<store.UISession>;

export function SetRestoreOpen(arg1:boolean):Promise<store.UISession>;

export function SetShowHiddenFolders(arg1:boolean):Promise<store.FolderVisibility>;

export function SetUISelection(arg1:string,arg2:string):Promise<store.UISession>;

export function StartAnalysisJob(arg1:string,arg2:string):Promise<cloud.JobStatus>;

export function SyncAllFolders():Promise<Array<store.FolderChange>>;

export function ToggleOpenFolder(arg1:string):Promise<store.UISession>;

export function ToggleOpenSeries(arg1:string):Promise<store.UISession>;

export function ToggleOpenStory(arg1:string):Promise<store.UISession>;

export function UpdateAct(arg1:number,arg2:store.ActInput):Promise<store.UpdatedResult>;

export function UpdateChapter(arg1:number,arg2:store.ChapterInput):Promise<store.UpdatedResult>;

export function UpdateCharacter(arg1:number,arg2:store.CharacterInput):Promise<store.UpdatedResult>;

export function UpdateSeries(arg1:number,arg2:store.SeriesInput):Promise<store.UpdatedResult>;

export function UpdateSeriesBible(arg1:number,arg2:string):Promise<store.UpdatedResult>;

export function UpdateSeriesDoc(arg1:number,arg2:store.SeriesDocInput):Promise<store.UpdatedResult>;

export function UpdateStory(arg1:number,arg2:store.StoryInput):Promise<store.UpdatedResult>;

export function WriteDiskFile(arg1:store.DiskFileWrite):Promise<store.DiskFile>;

export function WriteDiskFileSection(arg1:string,arg2:string,arg3:number,arg4:string):Promise<store.DiskFile>;

export function WriteHeaderFile(arg1:store.HeaderFileWrite):Promise<store.HeaderFile>;
